import  Mongoose  from "mongoose";

const orderSchema=Mongoose.Schema({
    user:{
        type:Mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
          },
        orderitems:[{
            name:{type:String,required:true},
            qty:{type:Number,required:true},
            image:{type:String,requird:true},
            price:{type:Number,required:true},
            product:{
                type:Mongoose.Schema.Types.ObjectId,
                required:true,
                ref:'product'
            }
        }],
        shippingaddress:{
         address:{type:String,required:true},
         city:{type:String,requird:true},
         postalcode:{type:String,requird:true},
         country:{type:String,required:true}
        },
        paymentmethod:{
            type:String,
            requied:true
        },
        paymentresult:{
            id:{type:String},
            status:{type:String},
            updatetime:{type:String},
            emailaddress:{type:String}
        },
        taxprice:{
           type:Number,
           required:true,
           default:0.0, 
        },
        shippingprice:{
            type:Number,
            required:true,
            default:0.0, 
         },
         totalprice:{
            type:Number,
            required:true,
            default:0.0, 
         },
         ispaid:{
             type:Boolean,
             required:true,
             default:false
         },
         paidat:{
         type:Date
         },
         isdelivered:{
             type:Boolean,
             required:true,
             default:false
         },
         deliveredat:{
          type:Date   
         }
                },{
                      timestamps:true
                  }
)
const Order=Mongoose.model('Order',orderSchema);
export default Order;